baseurl = "https://tily.github.io/recital/"
languageCode = "en-us"
theme = "hugo-recital"
title = "R E C I T A L"

[params.pronunciation]
"'em" = "m"
"'mo" = "mòʊ"
"'til" = "tɪl"
"10" = ""
"1st" = ""
"20's" = ""
"2nd" = ""
"3rd" = ""
"45's" = ""
"4th" = ""
"9" = ""
"a" = ""
"about" = "əbάʊt"
"abstract" = "æbstrˈækt"
"act" = "ˈækt"
"addict" = "ˈædɪkt"
"admit" = "ədmít"
"adored" = "ədɔ́rd"
"advocates" = "ǽdvəkəts"
"africa" = "ˈæfrɪkə"
"against" = "əgèɪnst"
"aight" = ""
"ain't" = "éɪnt"
"airplay" = ""
"aka" = "ɑ́kə"
"all" = "ˈɔːl"
"allan" = "ˈælən"
"alone" = "əlˈəʊn"
"always" = "ˈɔːlweɪz"
"amping" = ""
"amps" = ""
"an" = " ən"
"and" = " ən"
"another" = "ənˈʌðɚ"
"any" = "éni"
"appreciated" = "əpríʃièɪtɪd"
"are" = " ɚ"
"arm" = "άɚm"
"arrest" = "ərést"
"as" = " əz"
"ask" = "ˈæsk"
"ass" = "ˈæs"
"assassin" = "əsˈæsn"
"at" = " ət"
"average" = "ˈævrɪdʒ"
"away" = "əˈweɪ"
"ayo" = "éɪoʊ"
"baby" = "béɪbi"
"back" = "bˈæk"
"backflip" = ""
"backtrack" = "bǽktræ̀k"
"bait" = "beɪt"
"ball" = "bˈɔːl"
"balling" = "bɔ́lɪŋ"
"bang" = "bˈæŋ"
"bar" = "bάɚ"
"bars" = "bɑ́rz"
"baseheads" = ""
"basin'" = "béɪsn"
"be" = " bi"
"beat" = "bíːt"
"beats" = "bíts"
"bebop" = "bíːbɑp"
"been" = " bɪn"
"beepers" = "bípɚz"
"before" = "bɪfˈɔɚ"
"begin" = "bəgín"
"being" = "bíːɪŋ"
"bent" = "bént"
"betting" = "‐ṭɪŋ"
"beyond" = "bɪάnd"
"bigger" = "ˈbɪɡɚ"
"bit" = "bít"
"bitch" = "bítʃ"
"bitches" = "ˈbɪtʃɪz"
"black" = "blˈæk"
"blame" = "bleɪm"
"blaming" = "bléɪmɪŋ"
"blasted" = "ˈblæst.ɪd"
"blend" = "blénd"
"blessed" = "blésɪd"
"blind" = "blάɪnd"
"block" = "blάk"
"blocks" = "blɑ́ks"
"blunt" = "blˈʌnt"
"blunts" = "blʌ́nts"
"bobby" = "bάbi"
"body" = "bάdi"
"bona" = "bóʊnə"
"booga" = ""
"booking" = "bʊ́kɪŋ"
"boom" = "búːm"
"booty" = "búːṭi"
"born" = "bˈɔɚn"
"botch" = "bάtʃ"
"both" = "bˈəʊθ"
"bounce" = "bάʊns"
"box" = "bάks"
"breaks" = "bɹeɪks"
"breath" = "bréθ"
"bring" = "bríŋ"
"bringing" = "brɪ́ŋɪŋ"
"broad" = "brˈɔːd"
"broken" = "bróʊkn"
"brother" = "brˈʌðɚ"
"brothers" = "brʌ́ðɚz"
"brown" = "brάʊn"
"buddha" = "búːdə"
"building" = "bíldɪŋ"
"bullet" = "bˈʊlɪt"
"bullets" = "bʊ́ləts"
"but" = " bət"
"by" = "bɑɪ"
"call" = "kˈɔːl"
"called" = "kɔːld"
"came" = "keɪm"
"can" = " kn"
"can't" = "kˈæːnt"
"capone" = "kəpˈəʊn"
"capsule" = "kˈæpsl"
"cars" = "kɑ́rz"
"case" = "keɪs"
"cash" = "kˈæʃ"
"casket" = "kˈæskɪt"
"catch" = "kˈætʃ"
"catching" = "kǽtʃɪŋ"
"caught" = "kˈɔːt"
"cause" = "kˈɔːz"
"cee" = ""
"chain" = "ˈʧeːjn"
"chamber" = "tʃéɪmbə"
"champs" = "tʃǽmps"
"chandon" = "tʃǽndɪn"
"chasing" = "tʃéɪsɪŋ"
"cheetah" = "tʃíːṭə"
"chick" = "tʃík"
"chicks" = "tʃɪ́ks"
"children" = "tʃíldrən"
"christ" = "krάɪst"
"city" = "síṭi"
"claim" = "kleɪm"
"click" = "klík"
"clothes" = "klóʊz"
"cocaine" = "kəʊkéɪn"
"cock" = "kάk"
"code" = "kˈəʊd"
"coke" = "kóʊk"
"come" = "kˈʌm"
"composition" = "kὰmpəzíʃən"
"continua" = ""
"continue" = "kəntínjuː"
"cops" = "kɒps"
"corner" = "kˈɔɚnɚ"
"corners" = "kɔ́rnɚz"
"correct" = "kərékt"
"cos" = "kάs"
"could" = " kəd"
"couldn't" = "kˈʊdnt"
"cousin" = "kˈʌzn"
"crab" = "krˈæb"
"crack" = "krˈæk"
"crackhead" = ""
"cracks" = "krǽks"
"credit" = "krédɪt"
"creeps" = "kríps"
"crew" = "krúː"
"crews" = "krúz"
"crime" = "krάɪm"
"criminal" = "krímənl"
"cris'" = "krɪ́s"
"cum" = "kʊm"
"cursions" = ""
"customers" = "kʌ́stəmɚz"
"cycles" = "sáɪkəlz"
"daddy" = "dˈædi"
"damn" = "dˈæm"
"dance" = "dˈæns"
"dancing" = "ˈdæn.sɪŋ"
"danger" = "déɪndʒə"
"dangerous" = "déɪndʒrəs"
"date" = "deɪt"
"day" = "déɪ"
"daylight" = "déɪlὰɪt"
"days" = "ˈdeɪz"
"death" = "déθ"
"dee" = "dí"
"deep" = "díːp"
"defeat" = "dɪfíːt"
"defined" = "dəˈfaɪnd"
"delivering" = "dɪlɪ́vɚɪŋ"
"delta" = "déltə"
"deserve" = "dɪzˈɚːv"
"destiny" = "déstəni"
"dick" = "dík"
"did" = "díd"
"dipped" = "dɪ́pt"
"dishing" = "dɪ́ʃɪŋ"
"diss" = "dɪs"
"do" = "díṭoʊ"
"does" = "dˈʌz"
"dog" = "dˈɔːg"
"doin" = "dúɪn"
"doing" = "dúːɪŋ"
"don't" = "dˈəʊnt"
"done" = "dˈʌn"
"dope" = "dˈəʊp"
"dough" = "dˈəʊ"
"drastic" = "drˈæstɪk"
"dream" = "dríːm"
"dreams" = "drímz"
"drifting" = "drɪ́ftɪŋ"
"drinking" = "drɪ́ŋkɪŋ"
"drop" = "drάp"
"dropped" = "drɑ́pt"
"drops" = "drɑ́ps"
"drug" = "drˈʌg"
"dungeons" = "dʌ́ndʒənz"
"dykes" = "dáɪks"
"e" = ""
"each" = "íːtʃ"
"earlier" = "ɝ́liɚ"
"eats" = "íts"
"edgar" = "édgɚ"
"eighteens" = "eɪtínz"
"either" = "íːðɚ"
"enough" = "ɪnˈʌf"
"equivalent" = "ɪkwívlənt"
"erasin'" = ""
"especially" = "espéʃəli"
"even" = "íːvn"
"ever" = "évɚ"
"every" = "évri"
"everybody" = "évribὰdi"
"everyday" = "évridèɪ"
"everything" = "évriθìŋ"
"ex" = "èks"
"exist" = "egzíst"
"expect" = "ekspékt"
"expected" = "ɪksˈpɛktɪd"
"extreme" = "ekstríːm"
"face" = "feɪs"
"fact" = "fˈækt"
"fair" = "féɚ"
"fake" = "féɪk"
"fall" = "fˈɔːl"
"fame" = "feɪm"
"feel" = "fíːl"
"fell" = "fél"
"few" = "fjúː"
"fide" = "fáɪd"
"fiends" = "fíndz"
"fight" = "fάɪt"
"figures" = "fɪ́ɡjɚz"
"filled" = "fɪ́ld"
"finally" = "fάɪnəli"
"find" = "fάɪnd"
"finger" = "fíŋgɚ"
"first" = "fˈɚːst"
"fish" = "fíʃ"
"fix" = "fíks"
"fixture" = "fíkstʃɚ"
"flex" = "fléks"
"flip" = "flíp"
"flipped" = "flɪ́pt"
"flooded" = "flʌ́dəd"
"floss" = "flάs"
"flow" = "flˈəʊ"
"fly" = "flάɪ"
"foes" = "fóʊz"
"for" = " fɚ"
"force" = "fˈɔɚs"
"fore" = "fˈɔɚ"
"foreign" = "fˈɔːrən"
"forever" = "fərévɚ"
"freaks" = "fríks"
"friend" = "frénd"
"from" = "frəm"
"front" = "frˈʌnt"
"frustrated" = "ˈfɻʌstɻeɪɾɪd"
"fuck" = "fˈʌk"
"fucked" = "fʌkt"
"fucking" = "ˈfʌkɪŋ"
"full" = "fˈʊl"
"funky" = "fˈʌŋki"
"g" = ""
"gaining" = "ɡéɪnɪŋ"
"game" = "géɪm"
"gangsta" = "ɡǽŋstə"
"gat" = "gˈæt"
"gauges" = "ɡéɪdʒəz"
"gave" = "géɪv"
"get" = "gét"
"gets" = "ɡɛ́ts"
"getting" = "ˈɡɛtɪŋ"
"girl" = "gˈɚːl"
"girlies" = ""
"give" = "gív"
"glad" = "glˈæd"
"go" = "góʊ"
"god" = "gάd"
"goners" = ""
"good" = "gˈʊd"
"goods" = "gˈʊdz"
"got" = "gάt"
"gotta" = "gάṭə"
"gradually" = "grˈædʒuəli"
"grants" = "ɡrǽnts"
"grass" = "grˈæs"
"gravy" = "gréɪvi"
"grazed" = "ɡréɪzd"
"great" = "gréɪt"
"green" = "gríːn"
"greet" = "gríːt"
"ground" = "grάʊnd"
"group" = "grúːp"
"guard" = "gάɚd"
"gunfights" = "ɡʌ́nfàɪts"
"guns" = "ɡʌnz"
"had" = "hˈæd"
"half" = "hˈæf"
"hand" = "hˈænd"
"hanging" = "hǽŋɪŋ"
"hard" = "hάɚd"
"hardest" = "hɑ́rdəst"
"have" = " həv"
"having" = "hˈævɪŋ"
"he's" = "hiːz"
"head" = "héd"
"hear" = "híɚ"
"heard" = "hˈɚːd"
"hearst" = "hɝ́st"
"heat" = "híːt"
"held" = "héld"
"hell" = "hél"
"her" = " ɚ"
"high" = "hάɪ"
"hijack" = "hάɪdʒ`æk"
"him" = " ɪm"
"hip" = "híp"
"his" = " ɪz"
"hit" = "hít"
"hittin'" = ""
"hitting" = "hɪ́tɪŋ"
"hoes" = "hóʊz"
"hold" = "hˈəʊld"
"holding" = "ˈhoːldɪŋ"
"holes" = "hóʊlz"
"holmes" = "hóʊmz"
"honest" = "άnəst"
"hooked" = "hʊkt"
"hop" = "hάp"
"hostages" = "hɑ́stədʒəz"
"hot" = "hάt"
"hottest" = "hɑ́təst"
"houston" = "júːstən"
"how" = "hάʊ"
"hughes" = "hjuːz"
"huh" = "hʌ̃"
"hustle" = "hˈʌsl"
"i" = ""
"i'll" = "ɑɪl"
"i'm" = "ɑɪm"
"i've" = "ɑɪv"
"ice" = "ɪs"
"if" = "íf"
"in" = "iːn"
"inanimate" = "ìnˈænəmət"
"inflictin'" = ""
"infor" = ""
"inhale" = "ɪnhéɪl"
"inside" = "ìnsάɪd"
"intelligence" = "ɪntélədʒəns"
"investments" = "ɪnvɛ́stmənts"
"is" = " ɪz"
"island" = "άɪlənd"
"it" = "ít"
"it's" = "ɪts"
"its" = "ɪts"
"j" = ""
"jaw" = "dʒˈɔː"
"jay" = "dʒeɪ"
"jazz" = "dʒˈæz"
"jerk" = "dʒˈɚːk"
"jet" = "dʒét"
"jetting" = "dʒɛ́tɪŋ"
"john" = "dʒάn"
"junkie" = "dʒˈʌŋki"
"just" = "dʒˈʌst"
"justification" = "dʒ`ʌstəfɪkéɪʃən"
"keep" = "kíːp"
"keeps" = "kíps"
"kickin'" = ""
"kids" = "kɪ́dz"
"knocked" = "nɑ́kt"
"know" = "nˈəʊ"
"knowledge" = "nάlɪdʒ"
"lake" = "leɪk"
"lamp" = "lˈæmp"
"langston" = "lǽŋstən"
"large" = "lάɚdʒ"
"last" = "lˈæst"
"laughing" = "ˈlɑːfɪŋ"
"lay" = "leɪ"
"lead" = "léd"
"learned" = "lˈɚːnɪd"
"learning" = "lˈɚːnɪŋ"
"least" = "líːst"
"leave" = "líːv"
"left" = "léft"
"legal" = "líːgl"
"let's" = "lèts"
"leverage" = "lévrɪdʒ"
"life" = "lάɪf"
"like" = "lάɪk"
"listen" = "lísn"
"listening" = "lɪ́sənɪŋ"
"live" = "lάɪv"
"living" = "lívɪŋ"
"lly" = ""
"lo" = "lˈəʊ"
"lobby" = "lάbi"
"longevity" = "lɑndʒévəṭi"
"looing" = ""
"look" = "lˈʊk"
"looking" = "lʊ́kɪŋ"
"lp" = "élpíː"
"luxury" = "lˈʌkʃri"
"m16" = ""
"mac" = "mˈæk"
"mac's" = "mǽks"
"made" = "meɪ̯d"
"maintain" = "meɪnˈteɪn"
"make" = "meɪk"
"making" = "méɪkɪŋ"
"man" = "mˈæn"
"many" = "méni"
"mat" = "mˈæt"
"mation" = ""
"max" = "mˈæks"
"may" = "meɪ"
"maybe" = "ˈmeɪbi"
"maze" = "méɪz"
"me" = " mi"
"measuring" = "‐ʒrɪŋ"
"mega" = "mégə"
"memories" = "mɛ́mɚiz"
"mental" = "ménṭl"
"merciless" = "ˈmɜːsɪləs"
"mess" = "més"
"michael" = "mάɪkl"
"mics" = ""
"mind" = "mάɪnd"
"mode" = "mˈəʊd"
"moets" = ""
"money" = "mˈʌni"
"monkey" = "mˈʌŋki"
"motherfucker" = "mʌ́ðɚfʌ́kɚ"
"motherfuckers" = "mʌ́ðɚfʌ́kɚz"
"motherland" = "mʌ́ðɚlæ̀nd"
"mouth" = "mάʊθ"
"move" = "múːv"
"moves" = "múvz"
"music" = "mjúːzɪk"
"musically" = "‐kəli"
"musician" = "mjuːzíʃən"
"must" = " məs"
"my" = "mɑɪ"
"name" = "néɪm"
"nana" = "nˈænə"
"naw" = "nɑ́"
"need" = "níːd"
"nega" = ""
"never" = "névɚ"
"new" = "núː"
"next" = "nékst"
"nice" = "nάɪs"
"nigga" = ""
"niggas" = ""
"night" = "nάɪt"
"nights" = "nάɪts"
"nikes" = "náɪkiz"
"no" = "nóʊ"
"none" = "nˈʌn"
"nope" = "nˈəʊp"
"not" = "nɒt"
"noted" = "nóʊṭɪd"
"nothing's" = "nʌ́θɪŋz"
"nothingness" = "nʌ́θɪŋnəs"
"now" = "nάʊ"
"object" = "άbdʒɪkt"
"of" = " v"
"off" = "ɔːf"
"okay" = "`əʊkéɪ"
"omen" = "ˈəʊmen"
"on" = "ɑn"
"once" = "wˈʌns"
"one" = "wˈʌn"
"only" = "ˈəʊnli"
"or" = "ə"
"other" = "ˈʌðɚ"
"out" = "άʊt"
"over" = "òʊvɚ"
"overseas" = "òʊvɚsíːz"
"own" = "ˈəʊn"
"packed" = "pˈækt"
"packs" = "pǽks"
"pager" = "péɪdʒə"
"pain" = "peɪn"
"pair" = "péɚ"
"parallel" = "pˈærəlèl"
"part" = "pάɚt"
"participate" = "pɑɚtísəpèɪt"
"passing" = "pˈæsɪŋ"
"past" = "pˈæst"
"paved" = "péɪvd"
"peepholes" = ""
"pen" = "pén"
"peoples" = "pípəlz"
"phony" = "ˈ-fəni"
"picked" = "pɪ́kt"
"picture" = "píktʃɚ"
"pj's" = "píːdʒéɪz"
"pl" = ""
"place" = "pleɪs"
"planted" = "plǽntəd"
"plastic" = "plˈæstɪk"
"plateau" = "plˈætəʊ"
"plays" = "pléɪz"
"plus" = "plˈʌs"
"pockets" = "pɑ́kəts"
"poe" = "pˈəʊ"
"poet" = "pˈəʊət"
"pointed" = "pˈɔɪnṭɪd"
"pop" = "pάp"
"popped" = "pɑ́pt"
"pops" = "pάps"
"positivity" = ""
"pots" = "pɑ́ts"
"power" = "pάʊɚ"
"praying" = "préɪɪŋ"
"prey" = "pɹeɪ"
"price" = "prάɪs"
"probably" = "prάbəbli"
"prominent" = "prάmənənt"
"proof" = "prúːf"
"prosperous" = "prάsprəs"
"pulled" = "pʊ́ld"
"pulling" = "pʊ́lɪŋ"
"put" = "pˈʊt"
"puzzle" = "pˈʌzl"
"quest" = "kwést"
"quick" = "kwík"
"rack" = "rˈæk"
"raise" = "reɪz"
"ran" = "rˈæn"
"rap" = "rˈæp"
"rappers" = "rǽpɚz"
"raps" = "rǽps"
"rats" = "rǽts"
"realize" = "ríːəlὰɪz"
"record" = "rɪkˈɔɚd"
"relief" = "rɪlíːf"
"reminded" = "rimáɪndəd"
"reminiscing" = "rɛ̀mənɪ́sɪŋ"
"retarded" = "rɪtɑ́rdɪd"
"revolution" = "rèvəlúːʃən"
"rhyme" = "rάɪm"
"rhymes" = "ráɪmz"
"rhymin'" = ""
"rhythm" = "ríðm"
"right" = "rάɪt"
"rings" = "rɪ́ŋz"
"rip" = "ríp"
"rise" = "rάɪz"
"rock" = "rάk"
"rocks" = "rɒks"
"roll" = "rˈəʊl"
"rollie" = "róʊli"
"room" = "rúːm"
"rover" = "róʊvɚ"
"rt" = ""
"ruby" = "rúːbi"
"run" = "rˈʌn"
"running" = "rˈʌnɪŋ"
"said" = "séd"
"same" = "séɪm"
"sane" = "seɪn"
"save" = "sèɪv"
"saw" = "sˈɔː"
"say" = "seɪ"
"sayin'" = "séɪɪn"
"scarface" = "skɑ́rfèɪs"
"scream" = "skríːm"
"screen" = "skríːn"
"scripts" = "skrɪ́pts"
"scuffle" = "skˈʌfl"
"sea" = "síː"
"sean" = "ʃˈɔːn"
"see" = "síː"
"seems" = "siːmz"
"seen" = "síːn"
"sell" = "sél"
"sever" = "sévɚ"
"sewing" = "sˈəʊɪŋ"
"sewn" = "sˈəʊn"
"shake" = "ˈʃeɪk"
"shakespeare" = "ʃéɪkspɪɚ"
"she" = " ʃi"
"she'll" = "ʃiːl"
"shelter" = "ʃéltɚ"
"ship" = "ʃíp"
"shit" = "ʃít"
"shook" = "ʃˈʊk"
"shoot" = "ʃúːt"
"shootin'" = "ʃútɪn"
"show" = "ʃˈəʊ"
"sip" = "síp"
"sis" = "sís"
"sit" = "sít"
"sitting" = "‐ṭɪŋ"
"size" = "sάɪz"
"sleep" = "slíːp"
"sleeps" = "slíps"
"slide" = "slάɪd"
"slow" = "slˈəʊ"
"smith" = "smíθ"
"smoke" = "smˈəʊk"
"smooth" = "smúːð"
"snatching" = "snǽtʃɪŋ"
"sneakers" = "sníkɚz"
"sniffin'" = ""
"snitch" = "snítʃ"
"so" = "sˈəʊ"
"society" = "səsάɪəṭi"
"some" = "səm"
"spastic" = "spˈæstɪk"
"speak" = "spíːk"
"speed" = "spíːd"
"speeding" = "spídɪŋ"
"sphere" = "sfìɚ"
"spit" = "spít"
"spot" = "spάt"
"sprayed" = "spréɪd"
"squeeze" = "skwíːz"
"stairway" = "stɛ́rwèɪ"
"start" = "stάɚt"
"stash" = "stˈæʃ"
"state" = "steɪt"
"status" = "stéɪṭəs"
"steelo" = ""
"stepped" = "stɛ́pt"
"stick" = "stík"
"stickup" = ""
"still" = "stíl"
"stocks" = "stɑ́ks"
"stones" = "stóʊnz"
"store" = "stˈɔɚ"
"stories" = "stɔ́riz"
"straight" = "stréɪt"
"strays" = "stréɪz"
"street" = "stríːt"
"streets" = "stríts"
"strive" = "strάɪv"
"strong" = "strˈɔːŋ"
"stuck" = "stˈʌk"
"stuff" = "stˈʌf"
"suited" = "súːṭɪd"
"sun" = "sˈʌn"
"supporters" = "səpɔ́rtɚz"
"sure" = "ʃˈʊɚ"
"swing" = "swíŋ"
"swinging" = "swíŋɪŋ"
"t" = ""
"taken" = "téɪkn"
"talk" = "tˈɔːk"
"talking" = "tɔ́kɪŋ"
"tape" = "téɪp"
"tapes" = "téɪps"
"task" = "tˈæsk"
"teach" = "tíːtʃ"
"tec's" = ""
"teenager" = "‐èɪdʒɚ"
"tell" = "tél"
"ten" = "tén"
"testin'" = ""
"than" = " ðən"
"thank" = "θˈæŋk"
"that" = "ðˈæt"
"that's" = "ðˈæts"
"the" = " ðə "
"their" = " ðɚ"
"them" = " ðəm"
"then" = "ðen"
"there" = "ðéɚ"
"these" = "ðíːz"
"they" = "ðeɪ"
"they're" = "ðeɚ"
"thigh" = "θάɪ"
"thing" = "θíŋ"
"things" = "θɪŋz"
"think" = "θíŋk"
"thinking" = "θíŋkɪŋ"
"this" = "ðís"
"though" = "ðoʊ"
"thought" = "θˈɔːt"
"thoughts" = "θɔ́ts"
"three" = "θríː"
"through" = "θruː"
"tight" = "tάɪt"
"til" = "tɪl"
"till" = "tíl"
"time" = "tάɪm"
"times" = "taɪmz"
"tip" = "típ"
"titles" = "táɪtəlz"
"titus" = "tάɪṭəs"
"tivity" = ""
"to" = "toː"
"today's" = "tədéɪz"
"together" = "tʊgéðɚ"
"told" = "tˈəʊld"
"tongue" = "tˈʌŋ"
"too" = "túː"
"tougher" = "tʌ́fɚ"
"toward" = "tˈɔɚd"
"trace" = "tɹeɪs"
"tracks" = "trǽks"
"trapped" = "trǽpt"
"trash" = "trˈæʃ"
"treat" = "tríːt"
"tribe" = "trάɪb"
"trigger" = "trígɚ"
"triggers" = "trɪ́ɡɚz"
"truckload" = "trʌ́klòʊd"
"true" = "trúː"
"truth" = "trúːθ"
"try" = "trάɪ"
"tryna" = ""
"turn" = "tˈɚːn"
"tv" = "tíːvíː"
"type" = "tάɪp"
"u" = ""
"uh" = "ə"
"undressin'" = ""
"unit" = "júːnɪt"
"until" = "əntíl"
"up" = "ˈʌp"
"us" = " əs"
"use" = "júːz"
"used" = "júːzd"
"vacation" = "vəɪkéɪʃən"
"villains" = "vɪ́lənz"
"vitamin" = "vάɪṭəmɪn"
"walking" = "wɔ́kɪŋ"
"walls" = "wɔ́lz"
"want" = "wάnt"
"was" = " wəz"
"wasn't" = "wάznt"
"way" = "wéɪ"
"we" = " wi"
"we're" = "wɪɚ"
"weed" = "wíːd"
"well" = "wél"
"wesson" = "wɛ́sən"
"what" = "wάt"
"what's" = "wάts"
"whatever" = "wɑṭévɚ"
"when" = "wén"
"whenever" = "wenévɚ"
"where" = "wéɚ"
"which" = "wítʃ"
"white" = "wάɪt"
"who" = "húː"
"why" = "wάɪ"
"will" = "wíl"
"winner" = "wínɚ"
"winning" = "wɪ́nɪŋ"
"with" = "wìð"
"without" = "wɪðὰʊt"
"wives" = "wάɪvz"
"woman" = "wˈʊmən"
"word" = "wˈɚːd"
"words" = "wɜːdz"
"work" = "wˈɚːk"
"wouldn't" = "wˈʊdnt"
"wrist" = "ríst"
"write" = "rάɪt"
"y'all" = "jɑːl"
"ya" = "jɑ́"
"yeah" = "jéə"
"year" = "jíɚ"
"yes" = "jés"
"yo" = "jˈəʊ"
"york" = "jˈɔɚk"
"you" = " jʊ"
"you're" = "jˈʊɚ"
"young" = "jˈʌŋ"
"younger" = "jʌ́ŋɡɚ"
"your" = " jɚ"
"yup" = "jˈʌp"
"zone" = "zˈəʊn"
"zulu" = "zúːluː"
