baseurl = "https://tily.github.io/recital/"
languageCode = "en-us"
theme = "hugo-recital"
title = "R E C I T A L"

[params.pronunciation]
"'em" = "m"
"'mo" = "mòʊ"
"'til" = "tɪl"
"10" = ""
"1st" = ""
"20's" = ""
"2nd" = ""
"3rd" = ""
"45's" = ""
"4th" = ""
"9" = ""
"a" = ""
"about" = "əbάʊt"
"addict" = "ˈædɪkt"
"admit" = "ədmít"
"against" = "əgèɪnst"
"aight" = ""
"ain't" = "éɪnt"
"airplay" = ""
"all" = "ˈɔːl"
"always" = "ˈɔːlweɪz"
"amps" = ""
"an" = " ən"
"and" = " ən"
"another" = "ənˈʌðɚ"
"any" = "éni"
"are" = " ɚ"
"arm" = "άɚm"
"arrest" = "ərést"
"as" = " əz"
"assassin" = "əsˈæsn"
"at" = " ət"
"away" = "əˈweɪ"
"ayo" = "éɪoʊ"
"back" = "bˈæk"
"backflip" = ""
"backtrack" = "bǽktræ̀k"
"bait" = "beɪt"
"ball" = "bˈɔːl"
"balling" = "bɔ́lɪŋ"
"bang" = "bˈæŋ"
"bar" = "bάɚ"
"bars" = "bɑ́rz"
"baseheads" = ""
"basin'" = "béɪsn"
"be" = " bi"
"beat" = "bíːt"
"beats" = "bíts"
"been" = " bɪn"
"beepers" = "bípɚz"
"begin" = "bəgín"
"bent" = "bént"
"betting" = "‐ṭɪŋ"
"beyond" = "bɪάnd"
"bigger" = "ˈbɪɡɚ"
"bit" = "bít"
"bitch" = "bítʃ"
"bitches" = "ˈbɪtʃɪz"
"black" = "blˈæk"
"blame" = "bleɪm"
"blaming" = "bléɪmɪŋ"
"blasted" = "ˈblæst.ɪd"
"blend" = "blénd"
"blessed" = "blésɪd"
"blind" = "blάɪnd"
"block" = "blάk"
"blocks" = "blɑ́ks"
"blunt" = "blˈʌnt"
"blunts" = "blʌ́nts"
"body" = "bάdi"
"born" = "bˈɔɚn"
"bounce" = "bάʊns"
"box" = "bάks"
"breaks" = "bɹeɪks"
"breath" = "bréθ"
"bring" = "bríŋ"
"bringing" = "brɪ́ŋɪŋ"
"broad" = "brˈɔːd"
"broken" = "bróʊkn"
"brother" = "brˈʌðɚ"
"brothers" = "brʌ́ðɚz"
"buddha" = "búːdə"
"building" = "bíldɪŋ"
"bullet" = "bˈʊlɪt"
"bullets" = "bʊ́ləts"
"but" = " bət"
"call" = "kˈɔːl"
"came" = "keɪm"
"can" = " kn"
"capone" = "kəpˈəʊn"
"capsule" = "kˈæpsl"
"cars" = "kɑ́rz"
"case" = "keɪs"
"cash" = "kˈæʃ"
"casket" = "kˈæskɪt"
"catch" = "kˈætʃ"
"catching" = "kǽtʃɪŋ"
"caught" = "kˈɔːt"
"cause" = "kˈɔːz"
"cee" = ""
"chain" = "ˈʧeːjn"
"chamber" = "tʃéɪmbə"
"champs" = "tʃǽmps"
"chandon" = "tʃǽndɪn"
"cheetah" = "tʃíːṭə"
"chick" = "tʃík"
"chicks" = "tʃɪ́ks"
"children" = "tʃíldrən"
"christ" = "krάɪst"
"city" = "síṭi"
"claim" = "kleɪm"
"click" = "klík"
"clothes" = "klóʊz"
"cocaine" = "kəʊkéɪn"
"cock" = "kάk"
"coke" = "kóʊk"
"come" = "kˈʌm"
"composition" = "kὰmpəzíʃən"
"cops" = "kɒps"
"corner" = "kˈɔɚnɚ"
"corners" = "kɔ́rnɚz"
"correct" = "kərékt"
"could" = " kəd"
"couldn't" = "kˈʊdnt"
"cousin" = "kˈʌzn"
"crab" = "krˈæb"
"crack" = "krˈæk"
"crackhead" = ""
"cracks" = "krǽks"
"creeps" = "kríps"
"crew" = "krúː"
"crews" = "krúz"
"crime" = "krάɪm"
"criminal" = "krímənl"
"cris'" = "krɪ́s"
"cum" = "kʊm"
"customers" = "kʌ́stəmɚz"
"damn" = "dˈæm"
"danger" = "déɪndʒə"
"dangerous" = "déɪndʒrəs"
"date" = "deɪt"
"day" = "déɪ"
"daylight" = "déɪlὰɪt"
"death" = "déθ"
"dee" = "dí"
"deep" = "díːp"
"defeat" = "dɪfíːt"
"defined" = "dəˈfaɪnd"
"delta" = "déltə"
"dick" = "dík"
"did" = "díd"
"dipped" = "dɪ́pt"
"do" = "díṭoʊ"
"does" = "dˈʌz"
"dog" = "dˈɔːg"
"doin" = "dúɪn"
"don't" = "dˈəʊnt"
"done" = "dˈʌn"
"dough" = "dˈəʊ"
"dream" = "dríːm"
"dreams" = "drímz"
"drinking" = "drɪ́ŋkɪŋ"
"drop" = "drάp"
"drops" = "drɑ́ps"
"drug" = "drˈʌg"
"dungeons" = "dʌ́ndʒənz"
"dykes" = "dáɪks"
"e" = ""
"each" = "íːtʃ"
"earlier" = "ɝ́liɚ"
"eats" = "íts"
"eighteens" = "eɪtínz"
"either" = "íːðɚ"
"enough" = "ɪnˈʌf"
"equivalent" = "ɪkwívlənt"
"erasin'" = ""
"even" = "íːvn"
"ever" = "évɚ"
"everyday" = "évridèɪ"
"extreme" = "ekstríːm"
"face" = "feɪs"
"fact" = "fˈækt"
"fake" = "féɪk"
"fame" = "feɪm"
"fell" = "fél"
"few" = "fjúː"
"fiends" = "fíndz"
"fight" = "fάɪt"
"figures" = "fɪ́ɡjɚz"
"finally" = "fάɪnəli"
"finger" = "fíŋgɚ"
"first" = "fˈɚːst"
"fish" = "fíʃ"
"flip" = "flíp"
"flipped" = "flɪ́pt"
"flooded" = "flʌ́dəd"
"floss" = "flάs"
"flow" = "flˈəʊ"
"foes" = "fóʊz"
"for" = " fɚ"
"force" = "fˈɔɚs"
"foreign" = "fˈɔːrən"
"forever" = "fərévɚ"
"freaks" = "fríks"
"from" = "frəm"
"front" = "frˈʌnt"
"frustrated" = "ˈfɻʌstɻeɪɾɪd"
"fuck" = "fˈʌk"
"fucked" = "fʌkt"
"fucking" = "ˈfʌkɪŋ"
"full" = "fˈʊl"
"funky" = "fˈʌŋki"
"g" = ""
"gaining" = "ɡéɪnɪŋ"
"game" = "géɪm"
"gangsta" = "ɡǽŋstə"
"gat" = "gˈæt"
"gauges" = "ɡéɪdʒəz"
"gave" = "géɪv"
"get" = "gét"
"getting" = "ˈɡɛtɪŋ"
"girl" = "gˈɚːl"
"give" = "gív"
"goners" = ""
"good" = "gˈʊd"
"got" = "gάt"
"gotta" = "gάṭə"
"gradually" = "grˈædʒuəli"
"grants" = "ɡrǽnts"
"grass" = "grˈæs"
"grazed" = "ɡréɪzd"
"great" = "gréɪt"
"green" = "gríːn"
"greet" = "gríːt"
"group" = "grúːp"
"guard" = "gάɚd"
"gunfights" = "ɡʌ́nfàɪts"
"guns" = "ɡʌnz"
"had" = "hˈæd"
"hand" = "hˈænd"
"hard" = "hάɚd"
"have" = " həv"
"having" = "hˈævɪŋ"
"he's" = "hiːz"
"head" = "héd"
"hear" = "híɚ"
"heard" = "hˈɚːd"
"hearst" = "hɝ́st"
"heat" = "híːt"
"held" = "héld"
"hell" = "hél"
"her" = " ɚ"
"high" = "hάɪ"
"hijack" = "hάɪdʒ`æk"
"him" = " ɪm"
"his" = " ɪz"
"hit" = "hít"
"hittin'" = ""
"hitting" = "hɪ́tɪŋ"
"hoes" = "hóʊz"
"hold" = "hˈəʊld"
"holding" = "ˈhoːldɪŋ"
"holes" = "hóʊlz"
"holmes" = "hóʊmz"
"hostages" = "hɑ́stədʒəz"
"hot" = "hάt"
"hottest" = "hɑ́təst"
"houston" = "júːstən"
"how" = "hάʊ"
"huh" = "hʌ̃"
"hustle" = "hˈʌsl"
"i" = ""
"i'll" = "ɑɪl"
"i'm" = "ɑɪm"
"i've" = "ɑɪv"
"ice" = "ɪs"
"if" = "íf"
"in" = "iːn"
"inflictin'" = ""
"infor" = ""
"inhale" = "ɪnhéɪl"
"inside" = "ìnsάɪd"
"intelligence" = "ɪntélədʒəns"
"investments" = "ɪnvɛ́stmənts"
"is" = " ɪz"
"island" = "άɪlənd"
"it" = "ít"
"it's" = "ɪts"
"j" = ""
"jaw" = "dʒˈɔː"
"jay" = "dʒeɪ"
"jet" = "dʒét"
"jetting" = "dʒɛ́tɪŋ"
"john" = "dʒάn"
"just" = "dʒˈʌst"
"keep" = "kíːp"
"keeps" = "kíps"
"kickin'" = ""
"kids" = "kɪ́dz"
"knocked" = "nɑ́kt"
"know" = "nˈəʊ"
"lake" = "leɪk"
"lamp" = "lˈæmp"
"large" = "lάɚdʒ"
"last" = "lˈæst"
"laughing" = "ˈlɑːfɪŋ"
"lay" = "leɪ"
"lead" = "léd"
"learned" = "lˈɚːnɪd"
"learning" = "lˈɚːnɪŋ"
"left" = "léft"
"legal" = "líːgl"
"life" = "lάɪf"
"like" = "lάɪk"
"live" = "lάɪv"
"living" = "lívɪŋ"
"lo" = "lˈəʊ"
"lobby" = "lάbi"
"look" = "lˈʊk"
"luxury" = "lˈʌkʃri"
"m16" = ""
"mac" = "mˈæk"
"mac's" = "mǽks"
"made" = "meɪ̯d"
"maintain" = "meɪnˈteɪn"
"make" = "meɪk"
"making" = "méɪkɪŋ"
"man" = "mˈæn"
"many" = "méni"
"mat" = "mˈæt"
"mation" = ""
"max" = "mˈæks"
"maybe" = "ˈmeɪbi"
"maze" = "méɪz"
"me" = " mi"
"measuring" = "‐ʒrɪŋ"
"mega" = "mégə"
"mess" = "més"
"mics" = ""
"mind" = "mάɪnd"
"moets" = ""
"monkey" = "mˈʌŋki"
"motherfucker" = "mʌ́ðɚfʌ́kɚ"
"motherfuckers" = "mʌ́ðɚfʌ́kɚz"
"musician" = "mjuːzíʃən"
"must" = " məs"
"my" = "mɑɪ"
"name" = "néɪm"
"nana" = "nˈænə"
"naw" = "nɑ́"
"need" = "níːd"
"never" = "névɚ"
"new" = "núː"
"nice" = "nάɪs"
"nigga" = ""
"niggas" = ""
"nights" = "nάɪts"
"no" = "nóʊ"
"none" = "nˈʌn"
"nope" = "nˈəʊp"
"nothing's" = "nʌ́θɪŋz"
"now" = "nάʊ"
"of" = " v"
"off" = "ɔːf"
"okay" = "`əʊkéɪ"
"omen" = "ˈəʊmen"
"on" = "ɑn"
"once" = "wˈʌns"
"one" = "wˈʌn"
"only" = "ˈəʊnli"
"or" = "ə"
"other" = "ˈʌðɚ"
"out" = "άʊt"
"overseas" = "òʊvɚsíːz"
"packed" = "pˈækt"
"packs" = "pǽks"
"pain" = "peɪn"
"parallel" = "pˈærəlèl"
"part" = "pάɚt"
"participate" = "pɑɚtísəpèɪt"
"paved" = "péɪvd"
"peepholes" = ""
"pen" = "pén"
"peoples" = "pípəlz"
"picked" = "pɪ́kt"
"pj's" = "píːdʒéɪz"
"pl" = ""
"place" = "pleɪs"
"plateau" = "plˈætəʊ"
"plays" = "pléɪz"
"plus" = "plˈʌs"
"pockets" = "pɑ́kəts"
"pointed" = "pˈɔɪnṭɪd"
"popped" = "pɑ́pt"
"pots" = "pɑ́ts"
"price" = "prάɪs"
"probably" = "prάbəbli"
"prosperous" = "prάsprəs"
"pulled" = "pʊ́ld"
"pulling" = "pʊ́lɪŋ"
"put" = "pˈʊt"
"puzzle" = "pˈʌzl"
"quick" = "kwík"
"raise" = "reɪz"
"ran" = "rˈæn"
"rap" = "rˈæp"
"rappers" = "rǽpɚz"
"rats" = "rǽts"
"reminiscing" = "rɛ̀mənɪ́sɪŋ"
"revolution" = "rèvəlúːʃən"
"rhymes" = "ráɪmz"
"rhymin'" = ""
"rhythm" = "ríðm"
"right" = "rάɪt"
"rings" = "rɪ́ŋz"
"rip" = "ríp"
"rock" = "rάk"
"rocks" = "rɒks"
"roll" = "rˈəʊl"
"rollie" = "róʊli"
"rover" = "róʊvɚ"
"rt" = ""
"ruby" = "rúːbi"
"run" = "rˈʌn"
"running" = "rˈʌnɪŋ"
"said" = "séd"
"same" = "séɪm"
"sane" = "seɪn"
"save" = "sèɪv"
"saw" = "sˈɔː"
"say" = "seɪ"
"sayin'" = "séɪɪn"
"scarface" = "skɑ́rfèɪs"
"scream" = "skríːm"
"screen" = "skríːn"
"scripts" = "skrɪ́pts"
"scuffle" = "skˈʌfl"
"sean" = "ʃˈɔːn"
"see" = "síː"
"seen" = "síːn"
"sell" = "sél"
"sewing" = "sˈəʊɪŋ"
"sewn" = "sˈəʊn"
"she" = " ʃi"
"she'll" = "ʃiːl"
"shelter" = "ʃéltɚ"
"shit" = "ʃít"
"shook" = "ʃˈʊk"
"shoot" = "ʃúːt"
"shootin'" = "ʃútɪn"
"show" = "ʃˈəʊ"
"sip" = "síp"
"sit" = "sít"
"sitting" = "‐ṭɪŋ"
"sleep" = "slíːp"
"sleeps" = "slíps"
"slide" = "slάɪd"
"slow" = "slˈəʊ"
"smith" = "smíθ"
"smoke" = "smˈəʊk"
"smooth" = "smúːð"
"snatching" = "snǽtʃɪŋ"
"sneakers" = "sníkɚz"
"sniffin'" = ""
"snitch" = "snítʃ"
"so" = "sˈəʊ"
"some" = "səm"
"speed" = "spíːd"
"speeding" = "spídɪŋ"
"spit" = "spít"
"spot" = "spάt"
"sprayed" = "spréɪd"
"squeeze" = "skwíːz"
"stairway" = "stɛ́rwèɪ"
"start" = "stάɚt"
"stash" = "stˈæʃ"
"state" = "steɪt"
"steelo" = ""
"stepped" = "stɛ́pt"
"stickup" = ""
"stocks" = "stɑ́ks"
"stones" = "stóʊnz"
"stories" = "stɔ́riz"
"straight" = "stréɪt"
"strays" = "stréɪz"
"street" = "stríːt"
"streets" = "stríts"
"stuck" = "stˈʌk"
"stuff" = "stˈʌf"
"suited" = "súːṭɪd"
"sun" = "sˈʌn"
"sure" = "ʃˈʊɚ"
"swing" = "swíŋ"
"swinging" = "swíŋɪŋ"
"t" = ""
"taken" = "téɪkn"
"talk" = "tˈɔːk"
"talking" = "tɔ́kɪŋ"
"tape" = "téɪp"
"tapes" = "téɪps"
"task" = "tˈæsk"
"teach" = "tíːtʃ"
"tec's" = ""
"tell" = "tél"
"testin'" = ""
"than" = " ðən"
"that" = "ðˈæt"
"that's" = "ðˈæts"
"the" = " ðə "
"their" = " ðɚ"
"them" = " ðəm"
"then" = "ðen"
"there" = "ðéɚ"
"these" = "ðíːz"
"they" = "ðeɪ"
"thing" = "θíŋ"
"think" = "θíŋk"
"thinking" = "θíŋkɪŋ"
"this" = "ðís"
"though" = "ðoʊ"
"thought" = "θˈɔːt"
"thoughts" = "θɔ́ts"
"three" = "θríː"
"through" = "θruː"
"tight" = "tάɪt"
"til" = "tɪl"
"time" = "tάɪm"
"times" = "taɪmz"
"titles" = "táɪtəlz"
"titus" = "tάɪṭəs"
"to" = "toː"
"told" = "tˈəʊld"
"too" = "túː"
"tougher" = "tʌ́fɚ"
"trace" = "tɹeɪs"
"trapped" = "trǽpt"
"trash" = "trˈæʃ"
"trigger" = "trígɚ"
"triggers" = "trɪ́ɡɚz"
"try" = "trάɪ"
"tryna" = ""
"turn" = "tˈɚːn"
"tv" = "tíːvíː"
"type" = "tάɪp"
"u" = ""
"uh" = "ə"
"undressin'" = ""
"until" = "əntíl"
"up" = "ˈʌp"
"us" = " əs"
"use" = "júːz"
"vacation" = "vəɪkéɪʃən"
"villains" = "vɪ́lənz"
"vitamin" = "vάɪṭəmɪn"
"walking" = "wɔ́kɪŋ"
"walls" = "wɔ́lz"
"want" = "wάnt"
"was" = " wəz"
"wasn't" = "wάznt"
"way" = "wéɪ"
"we" = " wi"
"we're" = "wɪɚ"
"weed" = "wíːd"
"wesson" = "wɛ́sən"
"what" = "wάt"
"when" = "wén"
"whenever" = "wenévɚ"
"where" = "wéɚ"
"who" = "húː"
"will" = "wíl"
"winning" = "wɪ́nɪŋ"
"with" = "wìð"
"without" = "wɪðὰʊt"
"wives" = "wάɪvz"
"word" = "wˈɚːd"
"words" = "wɜːdz"
"wouldn't" = "wˈʊdnt"
"wrist" = "ríst"
"write" = "rάɪt"
"y'all" = "jɑːl"
"ya" = "jɑ́"
"yeah" = "jéə"
"yes" = "jés"
"yo" = "jˈəʊ"
"york" = "jˈɔɚk"
"you" = " jʊ"
"young" = "jˈʌŋ"
"younger" = "jʌ́ŋɡɚ"
"your" = " jɚ"
"yup" = "jˈʌp"
